# Generated by Django 3.0.4 on 2020-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_desc',
            field=models.CharField(default='Underwear Supplier', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(max_length=15),
        ),
    ]
