# Generated by Django 3.0.4 on 2020-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200425_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_lat',
            field=models.FloatField(default=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_long',
            field=models.FloatField(default=64.3),
            preserve_default=False,
        ),
    ]
