# Generated by Django 3.0.4 on 2020-04-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200425_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='representative',
            old_name='company_id',
            new_name='company',
        ),
    ]
